mcf: Fix compatibility with newer git (v6.2.3)
:Release Notes:
Since 2017-08-17 (git version 2.14.1.473.g3ec7d702a) using deprecated
git branch parameter "--set-upstream" causes an error. Replace it by
"--set-upstream-to".

:Detailed Notes:
https://git.kernel.org/pub/scm/git/git.git/commit/?id=52668846ea2d41ffbd87cda7cb8e492dea9f2c4d
says, it's deprecated since 2012-08-30 so hopefully all still supported
host distributions have new enough git to support "--set-upstream-to".

With git version 2.17.1 from Ubuntu 18.04 it fails with:

2018-08-16T14:45:32 WARNING __main__ checkout meta-lg-webos was tracking 'origin/refs/heads/@gld4tv' changing it to track 'origin/jansa/gld4tv-morty'
fatal: the '--set-upstream' option is no longer supported. Please use '--track' or '--set-upstream-to' instead.
Traceback (most recent call last):
  File "./mcf", line 901, in <module>
    update_layers(srcdir)
  File "./mcf", line 478, in update_layers
    if reposanitycheck(layer) != 0:
  File "./mcf", line 647, in reposanitycheck
    echo_check_call('git branch --set-upstream %s %s' % (newbranch, remotebranch))
  File "./mcf", line 48, in echo_check_call
    return str(subprocess.check_output(cmd, shell=True), encoding='utf-8', errors='strict')
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'git branch --set-upstream jansa/gld4tv-morty origin/jansa/gld4tv-morty' returned non-zero exit status 128.

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[PLAT-64785] CCC: Update build script for Ubuntu 18.04 II

Change-Id: I0dbb599a3b23b2635dc3e8f82a291ee4dab6e464
Reviewed-on: http://gpro.lgsvl.com/214313
Build: Martin Jansa <martin.jansa@lge.com>
Reviewed-by: Martin Jansa <martin.jansa@lge.com>
Tested-by: Martin Jansa <martin.jansa@lge.com>
Reviewed-by: Susan Montooth <susan.montooth@lge.com>